name: Front-end CI/CD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  paths:
      - 'front-end2/**'

jobs:
  deploy-front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: af-south-1
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          cd front-end2
          npm i
          npx tsc
      - name: Sync files to S3 bucket
        run: |
          cd front-end2
          ls
          aws s3 sync . s3://spellit --delete